//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RewardPointApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:DebitCardRewardPointAPI", ConfigurationName="RewardPointApi.DebitCardRewardPointAPI")]
    public interface DebitCardRewardPointAPI
    {
        
        // CODEGEN: Generating message contract since the operation CurrentMonthStmtRPBal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/CurrentMonthStmtRPBal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RewardPointApi.CurrentMonthStmtRPBalResponse1 CurrentMonthStmtRPBal(RewardPointApi.CurrentMonthStmtRPBalRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/CurrentMonthStmtRPBal", ReplyAction="*")]
        System.Threading.Tasks.Task<RewardPointApi.CurrentMonthStmtRPBalResponse1> CurrentMonthStmtRPBalAsync(RewardPointApi.CurrentMonthStmtRPBalRequest1 request);
        
        // CODEGEN: Generating message contract since the operation HalfYearlyAndYearlyStmtRPBal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/HalfYearlyAndYearlyStmtRPBal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse1 HalfYearlyAndYearlyStmtRPBal(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/HalfYearlyAndYearlyStmtRPBal", ReplyAction="*")]
        System.Threading.Tasks.Task<RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse1> HalfYearlyAndYearlyStmtRPBalAsync(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RandomDateRangeRPBal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/RandomDateRangeRPBal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RewardPointApi.RandomDateRangeRPBalResponse1 RandomDateRangeRPBal(RewardPointApi.RandomDateRangeRPBalRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/RandomDateRangeRPBal", ReplyAction="*")]
        System.Threading.Tasks.Task<RewardPointApi.RandomDateRangeRPBalResponse1> RandomDateRangeRPBalAsync(RewardPointApi.RandomDateRangeRPBalRequest1 request);
        
        // CODEGEN: Generating message contract since the operation MonthWiseRPBalance is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/MonthWiseRPBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RewardPointApi.MonthWiseRPBalanceResponse1 MonthWiseRPBalance(RewardPointApi.MonthWiseRPBalanceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DebitCardRewardPointAPI/MonthWiseRPBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<RewardPointApi.MonthWiseRPBalanceResponse1> MonthWiseRPBalanceAsync(RewardPointApi.MonthWiseRPBalanceRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class CurrentMonthStmtRPBalRequest
    {
        
        private CurrentMonthStmtRPBalRequestRequestHeader requestHeaderField;
        
        private CurrentMonthStmtRPBalRequestRequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CurrentMonthStmtRPBalRequestRequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CurrentMonthStmtRPBalRequestRequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class CurrentMonthStmtRPBalRequestRequestHeader
    {
        
        private string userNameField;
        
        private string userPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class CurrentMonthStmtRPBalRequestRequestBody
    {
        
        private string accountnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountno
        {
            get
            {
                return this.accountnoField;
            }
            set
            {
                this.accountnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class CurrentMonthStmtRPBalResponse
    {
        
        private CurrentMonthStmtRPBalResponseResponseHeader responseHeaderField;
        
        private CurrentMonthStmtRPBalResponseTranDetails[] responseBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CurrentMonthStmtRPBalResponseResponseHeader ResponseHeader
        {
            get
            {
                return this.responseHeaderField;
            }
            set
            {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TranDetails", IsNullable=false)]
        public CurrentMonthStmtRPBalResponseTranDetails[] ResponseBody
        {
            get
            {
                return this.responseBodyField;
            }
            set
            {
                this.responseBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class CurrentMonthStmtRPBalResponseResponseHeader
    {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class CurrentMonthStmtRPBalResponseTranDetails
    {
        
        private string accountNumberField;
        
        private string monthlyEarnedField;
        
        private string monthlyRedeemField;
        
        private string monthlyExpiryField;
        
        private string nextMonthExpiryField;
        
        private string availableBalanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string monthlyEarned
        {
            get
            {
                return this.monthlyEarnedField;
            }
            set
            {
                this.monthlyEarnedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string monthlyRedeem
        {
            get
            {
                return this.monthlyRedeemField;
            }
            set
            {
                this.monthlyRedeemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string monthlyExpiry
        {
            get
            {
                return this.monthlyExpiryField;
            }
            set
            {
                this.monthlyExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nextMonthExpiry
        {
            get
            {
                return this.nextMonthExpiryField;
            }
            set
            {
                this.nextMonthExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string availableBalance
        {
            get
            {
                return this.availableBalanceField;
            }
            set
            {
                this.availableBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentMonthStmtRPBalRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.CurrentMonthStmtRPBalRequest CurrentMonthStmtRPBalRequest;
        
        public CurrentMonthStmtRPBalRequest1()
        {
        }
        
        public CurrentMonthStmtRPBalRequest1(RewardPointApi.CurrentMonthStmtRPBalRequest CurrentMonthStmtRPBalRequest)
        {
            this.CurrentMonthStmtRPBalRequest = CurrentMonthStmtRPBalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentMonthStmtRPBalResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.CurrentMonthStmtRPBalResponse CurrentMonthStmtRPBalResponse;
        
        public CurrentMonthStmtRPBalResponse1()
        {
        }
        
        public CurrentMonthStmtRPBalResponse1(RewardPointApi.CurrentMonthStmtRPBalResponse CurrentMonthStmtRPBalResponse)
        {
            this.CurrentMonthStmtRPBalResponse = CurrentMonthStmtRPBalResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class HalfYearlyAndYearlyStmtRPBalRequest
    {
        
        private HalfYearlyAndYearlyStmtRPBalRequestRequestHeader requestHeaderField;
        
        private HalfYearlyAndYearlyStmtRPBalRequestRequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HalfYearlyAndYearlyStmtRPBalRequestRequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public HalfYearlyAndYearlyStmtRPBalRequestRequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class HalfYearlyAndYearlyStmtRPBalRequestRequestHeader
    {
        
        private string userNameField;
        
        private string userPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class HalfYearlyAndYearlyStmtRPBalRequestRequestBody
    {
        
        private string accountnoField;
        
        private string reportTypeField;
        
        private string fromDateField;
        
        private string toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountno
        {
            get
            {
                return this.accountnoField;
            }
            set
            {
                this.accountnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string reportType
        {
            get
            {
                return this.reportTypeField;
            }
            set
            {
                this.reportTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class HalfYearlyAndYearlyStmtRPBalResponse
    {
        
        private HalfYearlyAndYearlyStmtRPBalResponseResponseHeader responseHeaderField;
        
        private HalfYearlyAndYearlyStmtRPBalResponseTranDetails[] responseBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HalfYearlyAndYearlyStmtRPBalResponseResponseHeader ResponseHeader
        {
            get
            {
                return this.responseHeaderField;
            }
            set
            {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TranDetails", IsNullable=false)]
        public HalfYearlyAndYearlyStmtRPBalResponseTranDetails[] ResponseBody
        {
            get
            {
                return this.responseBodyField;
            }
            set
            {
                this.responseBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class HalfYearlyAndYearlyStmtRPBalResponseResponseHeader
    {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class HalfYearlyAndYearlyStmtRPBalResponseTranDetails
    {
        
        private string accountNumberField;
        
        private string totalEarnedField;
        
        private string totalRedeemField;
        
        private string totalExpiryField;
        
        private string availableBalanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string totalEarned
        {
            get
            {
                return this.totalEarnedField;
            }
            set
            {
                this.totalEarnedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string totalRedeem
        {
            get
            {
                return this.totalRedeemField;
            }
            set
            {
                this.totalRedeemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string totalExpiry
        {
            get
            {
                return this.totalExpiryField;
            }
            set
            {
                this.totalExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string availableBalance
        {
            get
            {
                return this.availableBalanceField;
            }
            set
            {
                this.availableBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HalfYearlyAndYearlyStmtRPBalRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest HalfYearlyAndYearlyStmtRPBalRequest;
        
        public HalfYearlyAndYearlyStmtRPBalRequest1()
        {
        }
        
        public HalfYearlyAndYearlyStmtRPBalRequest1(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest HalfYearlyAndYearlyStmtRPBalRequest)
        {
            this.HalfYearlyAndYearlyStmtRPBalRequest = HalfYearlyAndYearlyStmtRPBalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HalfYearlyAndYearlyStmtRPBalResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse HalfYearlyAndYearlyStmtRPBalResponse;
        
        public HalfYearlyAndYearlyStmtRPBalResponse1()
        {
        }
        
        public HalfYearlyAndYearlyStmtRPBalResponse1(RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse HalfYearlyAndYearlyStmtRPBalResponse)
        {
            this.HalfYearlyAndYearlyStmtRPBalResponse = HalfYearlyAndYearlyStmtRPBalResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class RandomDateRangeRPBalRequest
    {
        
        private RandomDateRangeRPBalRequestRequestHeader requestHeaderField;
        
        private RandomDateRangeRPBalRequestRequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RandomDateRangeRPBalRequestRequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RandomDateRangeRPBalRequestRequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class RandomDateRangeRPBalRequestRequestHeader
    {
        
        private string userNameField;
        
        private string userPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class RandomDateRangeRPBalRequestRequestBody
    {
        
        private string accountnoField;
        
        private string fromDateField;
        
        private string toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountno
        {
            get
            {
                return this.accountnoField;
            }
            set
            {
                this.accountnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class RandomDateRangeRPBalResponse
    {
        
        private RandomDateRangeRPBalResponseResponseHeader responseHeaderField;
        
        private RandomDateRangeRPBalResponseTranDetails[] responseBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RandomDateRangeRPBalResponseResponseHeader ResponseHeader
        {
            get
            {
                return this.responseHeaderField;
            }
            set
            {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TranDetails", IsNullable=false)]
        public RandomDateRangeRPBalResponseTranDetails[] ResponseBody
        {
            get
            {
                return this.responseBodyField;
            }
            set
            {
                this.responseBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class RandomDateRangeRPBalResponseResponseHeader
    {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class RandomDateRangeRPBalResponseTranDetails
    {
        
        private string accountNumberField;
        
        private string availableRewardPointField;
        
        private string availableOnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string availableRewardPoint
        {
            get
            {
                return this.availableRewardPointField;
            }
            set
            {
                this.availableRewardPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AvailableOn
        {
            get
            {
                return this.availableOnField;
            }
            set
            {
                this.availableOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandomDateRangeRPBalRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.RandomDateRangeRPBalRequest RandomDateRangeRPBalRequest;
        
        public RandomDateRangeRPBalRequest1()
        {
        }
        
        public RandomDateRangeRPBalRequest1(RewardPointApi.RandomDateRangeRPBalRequest RandomDateRangeRPBalRequest)
        {
            this.RandomDateRangeRPBalRequest = RandomDateRangeRPBalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandomDateRangeRPBalResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.RandomDateRangeRPBalResponse RandomDateRangeRPBalResponse;
        
        public RandomDateRangeRPBalResponse1()
        {
        }
        
        public RandomDateRangeRPBalResponse1(RewardPointApi.RandomDateRangeRPBalResponse RandomDateRangeRPBalResponse)
        {
            this.RandomDateRangeRPBalResponse = RandomDateRangeRPBalResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class MonthWiseRPBalanceRequest
    {
        
        private MonthWiseRPBalanceRequestRequestHeader requestHeaderField;
        
        private MonthWiseRPBalanceRequestRequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MonthWiseRPBalanceRequestRequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MonthWiseRPBalanceRequestRequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class MonthWiseRPBalanceRequestRequestHeader
    {
        
        private string userNameField;
        
        private string userPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class MonthWiseRPBalanceRequestRequestBody
    {
        
        private string accountnoField;
        
        private string fromDateField;
        
        private string toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountno
        {
            get
            {
                return this.accountnoField;
            }
            set
            {
                this.accountnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class MonthWiseRPBalanceResponse
    {
        
        private MonthWiseRPBalanceResponseResponseHeader responseHeaderField;
        
        private MonthWiseRPBalanceResponseTranDetails[] responseBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MonthWiseRPBalanceResponseResponseHeader ResponseHeader
        {
            get
            {
                return this.responseHeaderField;
            }
            set
            {
                this.responseHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TranDetails", IsNullable=false)]
        public MonthWiseRPBalanceResponseTranDetails[] ResponseBody
        {
            get
            {
                return this.responseBodyField;
            }
            set
            {
                this.responseBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class MonthWiseRPBalanceResponseResponseHeader
    {
        
        private string responseCodeField;
        
        private string responseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bracbank.com")]
    public partial class MonthWiseRPBalanceResponseTranDetails
    {
        
        private string accountNumberField;
        
        private string previousMonthBalanceField;
        
        private string monthlyEarnedField;
        
        private string monthlyRedeemField;
        
        private string monthlyExpiryField;
        
        private string nextMonthlyExpiryField;
        
        private string availableBalanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string previousMonthBalance
        {
            get
            {
                return this.previousMonthBalanceField;
            }
            set
            {
                this.previousMonthBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string monthlyEarned
        {
            get
            {
                return this.monthlyEarnedField;
            }
            set
            {
                this.monthlyEarnedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string monthlyRedeem
        {
            get
            {
                return this.monthlyRedeemField;
            }
            set
            {
                this.monthlyRedeemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string monthlyExpiry
        {
            get
            {
                return this.monthlyExpiryField;
            }
            set
            {
                this.monthlyExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string nextMonthlyExpiry
        {
            get
            {
                return this.nextMonthlyExpiryField;
            }
            set
            {
                this.nextMonthlyExpiryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string availableBalance
        {
            get
            {
                return this.availableBalanceField;
            }
            set
            {
                this.availableBalanceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MonthWiseRPBalanceRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.MonthWiseRPBalanceRequest MonthWiseRPBalanceRequest;
        
        public MonthWiseRPBalanceRequest1()
        {
        }
        
        public MonthWiseRPBalanceRequest1(RewardPointApi.MonthWiseRPBalanceRequest MonthWiseRPBalanceRequest)
        {
            this.MonthWiseRPBalanceRequest = MonthWiseRPBalanceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MonthWiseRPBalanceResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bracbank.com", Order=0)]
        public RewardPointApi.MonthWiseRPBalanceResponse MonthWiseRPBalanceResponse;
        
        public MonthWiseRPBalanceResponse1()
        {
        }
        
        public MonthWiseRPBalanceResponse1(RewardPointApi.MonthWiseRPBalanceResponse MonthWiseRPBalanceResponse)
        {
            this.MonthWiseRPBalanceResponse = MonthWiseRPBalanceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface DebitCardRewardPointAPIChannel : RewardPointApi.DebitCardRewardPointAPI, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class DebitCardRewardPointAPIClient : System.ServiceModel.ClientBase<RewardPointApi.DebitCardRewardPointAPI>, RewardPointApi.DebitCardRewardPointAPI
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DebitCardRewardPointAPIClient() : 
                base(DebitCardRewardPointAPIClient.GetDefaultBinding(), DebitCardRewardPointAPIClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DebitCardRewardPointAPIQSPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebitCardRewardPointAPIClient(EndpointConfiguration endpointConfiguration) : 
                base(DebitCardRewardPointAPIClient.GetBindingForEndpoint(endpointConfiguration), DebitCardRewardPointAPIClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebitCardRewardPointAPIClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DebitCardRewardPointAPIClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebitCardRewardPointAPIClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DebitCardRewardPointAPIClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebitCardRewardPointAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RewardPointApi.CurrentMonthStmtRPBalResponse1 RewardPointApi.DebitCardRewardPointAPI.CurrentMonthStmtRPBal(RewardPointApi.CurrentMonthStmtRPBalRequest1 request)
        {
            return base.Channel.CurrentMonthStmtRPBal(request);
        }
        
        public RewardPointApi.CurrentMonthStmtRPBalResponse CurrentMonthStmtRPBal(RewardPointApi.CurrentMonthStmtRPBalRequest CurrentMonthStmtRPBalRequest)
        {
            RewardPointApi.CurrentMonthStmtRPBalRequest1 inValue = new RewardPointApi.CurrentMonthStmtRPBalRequest1();
            inValue.CurrentMonthStmtRPBalRequest = CurrentMonthStmtRPBalRequest;
            RewardPointApi.CurrentMonthStmtRPBalResponse1 retVal = ((RewardPointApi.DebitCardRewardPointAPI)(this)).CurrentMonthStmtRPBal(inValue);
            return retVal.CurrentMonthStmtRPBalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RewardPointApi.CurrentMonthStmtRPBalResponse1> RewardPointApi.DebitCardRewardPointAPI.CurrentMonthStmtRPBalAsync(RewardPointApi.CurrentMonthStmtRPBalRequest1 request)
        {
            return base.Channel.CurrentMonthStmtRPBalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RewardPointApi.CurrentMonthStmtRPBalResponse1> CurrentMonthStmtRPBalAsync(RewardPointApi.CurrentMonthStmtRPBalRequest CurrentMonthStmtRPBalRequest)
        {
            RewardPointApi.CurrentMonthStmtRPBalRequest1 inValue = new RewardPointApi.CurrentMonthStmtRPBalRequest1();
            inValue.CurrentMonthStmtRPBalRequest = CurrentMonthStmtRPBalRequest;
            return ((RewardPointApi.DebitCardRewardPointAPI)(this)).CurrentMonthStmtRPBalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse1 RewardPointApi.DebitCardRewardPointAPI.HalfYearlyAndYearlyStmtRPBal(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1 request)
        {
            return base.Channel.HalfYearlyAndYearlyStmtRPBal(request);
        }
        
        public RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse HalfYearlyAndYearlyStmtRPBal(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest HalfYearlyAndYearlyStmtRPBalRequest)
        {
            RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1 inValue = new RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1();
            inValue.HalfYearlyAndYearlyStmtRPBalRequest = HalfYearlyAndYearlyStmtRPBalRequest;
            RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse1 retVal = ((RewardPointApi.DebitCardRewardPointAPI)(this)).HalfYearlyAndYearlyStmtRPBal(inValue);
            return retVal.HalfYearlyAndYearlyStmtRPBalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse1> RewardPointApi.DebitCardRewardPointAPI.HalfYearlyAndYearlyStmtRPBalAsync(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1 request)
        {
            return base.Channel.HalfYearlyAndYearlyStmtRPBalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RewardPointApi.HalfYearlyAndYearlyStmtRPBalResponse1> HalfYearlyAndYearlyStmtRPBalAsync(RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest HalfYearlyAndYearlyStmtRPBalRequest)
        {
            RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1 inValue = new RewardPointApi.HalfYearlyAndYearlyStmtRPBalRequest1();
            inValue.HalfYearlyAndYearlyStmtRPBalRequest = HalfYearlyAndYearlyStmtRPBalRequest;
            return ((RewardPointApi.DebitCardRewardPointAPI)(this)).HalfYearlyAndYearlyStmtRPBalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RewardPointApi.RandomDateRangeRPBalResponse1 RewardPointApi.DebitCardRewardPointAPI.RandomDateRangeRPBal(RewardPointApi.RandomDateRangeRPBalRequest1 request)
        {
            return base.Channel.RandomDateRangeRPBal(request);
        }
        
        public RewardPointApi.RandomDateRangeRPBalResponse RandomDateRangeRPBal(RewardPointApi.RandomDateRangeRPBalRequest RandomDateRangeRPBalRequest)
        {
            RewardPointApi.RandomDateRangeRPBalRequest1 inValue = new RewardPointApi.RandomDateRangeRPBalRequest1();
            inValue.RandomDateRangeRPBalRequest = RandomDateRangeRPBalRequest;
            RewardPointApi.RandomDateRangeRPBalResponse1 retVal = ((RewardPointApi.DebitCardRewardPointAPI)(this)).RandomDateRangeRPBal(inValue);
            return retVal.RandomDateRangeRPBalResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RewardPointApi.RandomDateRangeRPBalResponse1> RewardPointApi.DebitCardRewardPointAPI.RandomDateRangeRPBalAsync(RewardPointApi.RandomDateRangeRPBalRequest1 request)
        {
            return base.Channel.RandomDateRangeRPBalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RewardPointApi.RandomDateRangeRPBalResponse1> RandomDateRangeRPBalAsync(RewardPointApi.RandomDateRangeRPBalRequest RandomDateRangeRPBalRequest)
        {
            RewardPointApi.RandomDateRangeRPBalRequest1 inValue = new RewardPointApi.RandomDateRangeRPBalRequest1();
            inValue.RandomDateRangeRPBalRequest = RandomDateRangeRPBalRequest;
            return ((RewardPointApi.DebitCardRewardPointAPI)(this)).RandomDateRangeRPBalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RewardPointApi.MonthWiseRPBalanceResponse1 RewardPointApi.DebitCardRewardPointAPI.MonthWiseRPBalance(RewardPointApi.MonthWiseRPBalanceRequest1 request)
        {
            return base.Channel.MonthWiseRPBalance(request);
        }
        
        public RewardPointApi.MonthWiseRPBalanceResponse MonthWiseRPBalance(RewardPointApi.MonthWiseRPBalanceRequest MonthWiseRPBalanceRequest)
        {
            RewardPointApi.MonthWiseRPBalanceRequest1 inValue = new RewardPointApi.MonthWiseRPBalanceRequest1();
            inValue.MonthWiseRPBalanceRequest = MonthWiseRPBalanceRequest;
            RewardPointApi.MonthWiseRPBalanceResponse1 retVal = ((RewardPointApi.DebitCardRewardPointAPI)(this)).MonthWiseRPBalance(inValue);
            return retVal.MonthWiseRPBalanceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RewardPointApi.MonthWiseRPBalanceResponse1> RewardPointApi.DebitCardRewardPointAPI.MonthWiseRPBalanceAsync(RewardPointApi.MonthWiseRPBalanceRequest1 request)
        {
            return base.Channel.MonthWiseRPBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RewardPointApi.MonthWiseRPBalanceResponse1> MonthWiseRPBalanceAsync(RewardPointApi.MonthWiseRPBalanceRequest MonthWiseRPBalanceRequest)
        {
            RewardPointApi.MonthWiseRPBalanceRequest1 inValue = new RewardPointApi.MonthWiseRPBalanceRequest1();
            inValue.MonthWiseRPBalanceRequest = MonthWiseRPBalanceRequest;
            return ((RewardPointApi.DebitCardRewardPointAPI)(this)).MonthWiseRPBalanceAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DebitCardRewardPointAPIQSPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DebitCardRewardPointAPIQSPort))
            {
                return new System.ServiceModel.EndpointAddress("http://172.25.15.41:9001/DebitCardRewardPointAPI/proxy-service/DebitCardRewardPoi" +
                        "ntAPI");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DebitCardRewardPointAPIClient.GetBindingForEndpoint(EndpointConfiguration.DebitCardRewardPointAPIQSPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DebitCardRewardPointAPIClient.GetEndpointAddress(EndpointConfiguration.DebitCardRewardPointAPIQSPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DebitCardRewardPointAPIQSPort,
        }
    }
}
